<script type="text/javascript">
//<![CDATA[
	var google_conversion_id = <?php echo $this->getAdwordsId() ?>;
	var google_conversion_language = "<?php echo $this->getLanguage() ?>";
	var google_conversion_format = "<?php echo $this->getFormat() ?>";
	var google_conversion_color = "<?php echo $this->getColor() ?>";
	var google_conversion_label = "<?php echo $this->getLabel() ?>";
	var google_conversion_value = <?php echo $this->getValue() ?>;
//]]>
</script>
<script type="text/javascript" src="<?php echo $this->getScriptUrl() ?>"></script>
<noscript>
<div style="display:inline;">
	<img height="1" width="1" style="border-style:none;" alt="" src="<?php echo $this->getImgSrc() ?>" />
</div>
</noscript>
