<script type="text/javascript">
//<![CDATA[
	var google_conversion_id = <?php echo $this->getAdwordsId() ?>;
	var google_custom_params = <?php echo $this->_getTagParams(); ?>;
	var google_remarketing_only = true;
//]]>
</script>
<script type="text/javascript" src="<?php echo $this->getScriptUrl() ?>"></script>
<noscript>
<div style="display:inline;">
	<img height="1" width="1" style="border-style:none;" alt="" src="<?php echo $this->getImgSrc() ?>" />
</div>
</noscript>
